/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.tree.intersection;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void hashIntersection() {

        BinaryTree<Integer> oneTree = new BinaryTree<>();
        oneTree.setRoot(new Node<>(10));
        oneTree.getRoot().setRight(new Node<>(50));
        oneTree.getRoot().setLeft(new Node<>(100));
        oneTree.getRoot().getRight().setRight(new Node<>(30));

        BinaryTree<Integer> twoTree = new BinaryTree<>();
        twoTree.setRoot(new Node<>(10));
        twoTree.getRoot().setRight(new Node<>(50));
        twoTree.getRoot().setLeft(new Node<>(1));
        twoTree.getRoot().getRight().setRight(new Node<>(3));

        assertEquals("[50, 10]", App.treeIntersection(oneTree, twoTree).toString());
    }
}