/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Node root =new Node(5);
        root.left =new Node(6);
        root.left.left =new Node(10);
        root.left.right =new Node(15);
        root.right = new Node(21);
        root.right.left =new Node(42);

       BinaryTree binaryTree =new BinaryTree();
       binaryTree.preOrder(root);
       binaryTree.inOrder(root);
       binaryTree.postOrder(root);

    }

}
