/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());



        HashTable newHashTable = new HashTable(7);
        newHashTable.add(0,"test add method");
        System.out.println(newHashTable.get(0));
        System.out.println(newHashTable.contains("test add method"));


    }
}
