/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        HashTable newHashTable = new HashTable(7);
        newHashTable.add(0,"test add method");
        System.out.println(newHashTable.get(0));
        System.out.println(newHashTable.contains("test add method"));


//    ______________________________CC33______________________________

        Map<String, String> mapOne = new HashMap<>();
        Map<String, String> mapTwo = new HashMap<>();

        mapOne.put("fond","enamored");
        mapOne.put("wrath","anger");
        mapOne.put("diligent","employed");
        mapOne.put("outfit","garb");
        mapOne.put("guide","usher");

        mapTwo.put("fond","averse");
        mapTwo.put("wrath","delight");
        mapTwo.put("diligent","idle");
        mapTwo.put("guide","follow");
        mapTwo.put("flow","jam");


       System.out.print ( HashTable.leftJoins(mapOne,mapTwo).toString());

    }
//
}
