/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion_sort;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        Assertions.assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
        int[] arr = new int[]{8, 4, 23, 42, 16, 15};
        int[] sortArr = new int[]{4, 8, 15, 16, 23, 42};
        Assertions.assertEquals(Arrays.toString(sortArr), Arrays.toString(App.insertionSort(arr)));
        Assertions.assertEquals(Arrays.toString(sortArr), Arrays.toString(App.mergeSort(arr)));
        Assertions.assertEquals(Arrays.toString(sortArr), Arrays.toString(App.quickSort(arr, 0, sortArr.length - 1)));
    }

}
